version: '3.8'
services:
  app:
    container_name: ga-update
    image: ga-update
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - 9000:9000
    restart: unless-stopped
    environment:
      - NODE_ENV=dev
      - PORT=9000
