
FROM node:18.12.1-alpine 
RUN apk update && apk add tzdata && apk --no-cache add curl
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
CMD ["npm", "run", "start:dev"]
